Traceback (most recent call last):
  File "sender.py", line 167, in <module>
    start()
  File "sender.py", line 34, in start
    with open(sys.argv[1]) as configFile:
IOError: [Errno 2] No such file or directory: '../resources/probing_configuration'
